spring:
    #数据源
    datasource:
        name: demo
        url: jdbc:mysql://127.0.0.1:3306/mmgame?useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    #日志
    profiles:
        active: dev

#http服务器
server:
    port: 9999

#netty配置
netty:
  port: 8090
  boss:
    thread:
        count: 2
  worker:
    thread:
        count: 4
  so:
    keepalive:  true
    backlog: 100


mybatis:
  # MyBatis注解形式扫描实体类路径
  type-aliases-package: com.example.model
  # MyBatis XML形式配置文件路径
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 通用mapper设置
mapper:
    not-empty: false
    identity: MYSQL

#线程池配置
threadpool:
  msg:
    core: 4
    max: 8
    queue: 0
    keepalive: 300
    prefix: msg
  eventbus:
    core: 1
    max: 1
    queue: 100
    keepalive: 300
    prefix: GameEvent-Bus

#游戏相关配置
game:
  request:
    queueMax: 100
    slowMillis: 1000
  session:
    timeout: 300
  user:
    timeout: 7200000
