// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMsg.proto

package com.example.pb;

public final class CommonMsg {
  private CommonMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SGameExceptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SGameException)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求id
     * </pre>
     *
     * <code>int32 reqId = 1;</code>
     */
    int getReqId();

    /**
     * <pre>
     * 异常码
     * </pre>
     *
     * <code>string errorCode = 2;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <pre>
     * 异常码
     * </pre>
     *
     * <code>string errorCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();

    /**
     * <pre>
     * 异常数据
     * </pre>
     *
     * <code>string errorData = 3;</code>
     */
    java.lang.String getErrorData();
    /**
     * <pre>
     * 异常数据
     * </pre>
     *
     * <code>string errorData = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorDataBytes();
  }
  /**
   * Protobuf id {@code SGameException}
   */
  public  static final class SGameException extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SGameException)
      SGameExceptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SGameException.newBuilder() to construct.
    private SGameException(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SGameException() {
      reqId_ = 0;
      errorCode_ = "";
      errorData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SGameException(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              reqId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              errorCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorData_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.pb.CommonMsg.internal_static_SGameException_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.pb.CommonMsg.internal_static_SGameException_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.pb.CommonMsg.SGameException.class, com.example.pb.CommonMsg.SGameException.Builder.class);
    }

    public static final int REQID_FIELD_NUMBER = 1;
    private int reqId_;
    /**
     * <pre>
     *请求id
     * </pre>
     *
     * <code>int32 reqId = 1;</code>
     */
    public int getReqId() {
      return reqId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorCode_;
    /**
     * <pre>
     * 异常码
     * </pre>
     *
     * <code>string errorCode = 2;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 异常码
     * </pre>
     *
     * <code>string errorCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorData_;
    /**
     * <pre>
     * 异常数据
     * </pre>
     *
     * <code>string errorData = 3;</code>
     */
    public java.lang.String getErrorData() {
      java.lang.Object ref = errorData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorData_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 异常数据
     * </pre>
     *
     * <code>string errorData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorDataBytes() {
      java.lang.Object ref = errorData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqId_ != 0) {
        output.writeInt32(1, reqId_);
      }
      if (!getErrorCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorCode_);
      }
      if (!getErrorDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqId_);
      }
      if (!getErrorCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorCode_);
      }
      if (!getErrorDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.pb.CommonMsg.SGameException)) {
        return super.equals(obj);
      }
      com.example.pb.CommonMsg.SGameException other = (com.example.pb.CommonMsg.SGameException) obj;

      boolean result = true;
      result = result && (getReqId()
          == other.getReqId());
      result = result && getErrorCode()
          .equals(other.getErrorCode());
      result = result && getErrorData()
          .equals(other.getErrorData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode().hashCode();
      hash = (37 * hash) + ERRORDATA_FIELD_NUMBER;
      hash = (53 * hash) + getErrorData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.pb.CommonMsg.SGameException parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.pb.CommonMsg.SGameException parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.pb.CommonMsg.SGameException parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.pb.CommonMsg.SGameException parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.pb.CommonMsg.SGameException prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf id {@code SGameException}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SGameException)
        com.example.pb.CommonMsg.SGameExceptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.pb.CommonMsg.internal_static_SGameException_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.pb.CommonMsg.internal_static_SGameException_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.pb.CommonMsg.SGameException.class, com.example.pb.CommonMsg.SGameException.Builder.class);
      }

      // Construct using com.example.pb.CommonMsg.SGameException.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reqId_ = 0;

        errorCode_ = "";

        errorData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.pb.CommonMsg.internal_static_SGameException_descriptor;
      }

      @java.lang.Override
      public com.example.pb.CommonMsg.SGameException getDefaultInstanceForType() {
        return com.example.pb.CommonMsg.SGameException.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.pb.CommonMsg.SGameException build() {
        com.example.pb.CommonMsg.SGameException result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.pb.CommonMsg.SGameException buildPartial() {
        com.example.pb.CommonMsg.SGameException result = new com.example.pb.CommonMsg.SGameException(this);
        result.reqId_ = reqId_;
        result.errorCode_ = errorCode_;
        result.errorData_ = errorData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.pb.CommonMsg.SGameException) {
          return mergeFrom((com.example.pb.CommonMsg.SGameException)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.pb.CommonMsg.SGameException other) {
        if (other == com.example.pb.CommonMsg.SGameException.getDefaultInstance()) return this;
        if (other.getReqId() != 0) {
          setReqId(other.getReqId());
        }
        if (!other.getErrorCode().isEmpty()) {
          errorCode_ = other.errorCode_;
          onChanged();
        }
        if (!other.getErrorData().isEmpty()) {
          errorData_ = other.errorData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.pb.CommonMsg.SGameException parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.pb.CommonMsg.SGameException) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqId_ ;
      /**
       * <pre>
       *请求id
       * </pre>
       *
       * <code>int32 reqId = 1;</code>
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <pre>
       *请求id
       * </pre>
       *
       * <code>int32 reqId = 1;</code>
       */
      public Builder setReqId(int value) {
        
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求id
       * </pre>
       *
       * <code>int32 reqId = 1;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorCode_ = "";
      /**
       * <pre>
       * 异常码
       * </pre>
       *
       * <code>string errorCode = 2;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 异常码
       * </pre>
       *
       * <code>string errorCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 异常码
       * </pre>
       *
       * <code>string errorCode = 2;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常码
       * </pre>
       *
       * <code>string errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常码
       * </pre>
       *
       * <code>string errorCode = 2;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorData_ = "";
      /**
       * <pre>
       * 异常数据
       * </pre>
       *
       * <code>string errorData = 3;</code>
       */
      public java.lang.String getErrorData() {
        java.lang.Object ref = errorData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 异常数据
       * </pre>
       *
       * <code>string errorData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorDataBytes() {
        java.lang.Object ref = errorData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 异常数据
       * </pre>
       *
       * <code>string errorData = 3;</code>
       */
      public Builder setErrorData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常数据
       * </pre>
       *
       * <code>string errorData = 3;</code>
       */
      public Builder clearErrorData() {
        
        errorData_ = getDefaultInstance().getErrorData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 异常数据
       * </pre>
       *
       * <code>string errorData = 3;</code>
       */
      public Builder setErrorDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SGameException)
    }

    // @@protoc_insertion_point(class_scope:SGameException)
    private static final com.example.pb.CommonMsg.SGameException DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.pb.CommonMsg.SGameException();
    }

    public static com.example.pb.CommonMsg.SGameException getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SGameException>
        PARSER = new com.google.protobuf.AbstractParser<SGameException>() {
      @java.lang.Override
      public SGameException parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SGameException(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SGameException> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SGameException> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.pb.CommonMsg.SGameException getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SGameException_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SGameException_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CommonMsg.proto\"E\n\016SGameException\022\r\n\005r" +
      "eqId\030\001 \001(\005\022\021\n\terrorCode\030\002 \001(\t\022\021\n\terrorDa" +
      "ta\030\003 \001(\tB\020\n\016com.example.pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SGameException_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SGameException_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SGameException_descriptor,
        new java.lang.String[] { "ReqId", "ErrorCode", "ErrorData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
